import { expect, test } from './fixtures.js'

test('canvas view controls switch views and lenses without stale placeholders', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('status-bar')).toContainText(/\d+ node schemas/, { timeout: 15_000 })
  const canvas = page.getByTestId('graph-canvas')
  await expect(canvas).toHaveAttribute('data-lens', 'standard')
  await expect(page.getByTestId('views-switcher')).toContainText('Graph')
  await expect(page.getByTestId('views-switcher')).toHaveAttribute('data-tooltip-label', 'View: how this tab is edited')
  await expect(page.getByTestId('lens-switcher')).toHaveAttribute('data-tooltip-label', 'Lens: how the graph is displayed')
  await page.getByTestId('views-switcher').click()
  await expect(page.getByRole('menu').filter({ hasText: 'Views' })).toContainText('Graph')
  await expect(page.getByRole('menu').filter({ hasText: 'Views' })).toContainText('App view')
  await page.getByRole('menuitemradio', { name: 'App view' }).click()
  await expect(page.getByTestId('app-view')).toBeVisible()
  await expect(page.getByTestId('views-switcher')).toContainText('App')
  await expect(page.getByTestId('app-view-toggle')).toHaveCount(0)
  await page.getByTestId('views-switcher').click()
  await page.getByRole('menuitemradio', { name: 'Graph' }).click()
  await expect(canvas).toBeVisible()
  await page.getByTestId('lens-switcher').click()
  await expect(page.getByRole('menu').filter({ hasText: 'Lenses' })).toBeVisible()
  await expect(page.getByText('App views - coming soon')).toHaveCount(0)
  await expect(page.getByRole('menuitemradio', { name: /Types/ })).toBeVisible()
  await expect(page.getByRole('menuitemradio', { name: /Data/ })).toBeVisible()
  await page.getByRole('menuitemradio', { name: /Types/ }).click()
  await expect(canvas).toHaveAttribute('data-lens', 'types')
  await page.getByTestId('lens-switcher').click()
  await page.getByRole('menuitemradio', { name: /Standard/ }).click()
  await expect(canvas).toHaveAttribute('data-lens', 'standard')
})

test('graph editor descriptor is named Graph', async ({ page }) => {
  await page.goto('/')
  await expect.poll(() => page.evaluate(() => window.__dinksterTest?.app.editors.get('graph')?.title)).toBe('Graph')
})

test('canvas view menus dismiss on outside pointerdown and global Escape', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('status-bar')).toContainText(/\d+ node schemas/, { timeout: 15_000 })
  const switcher = page.getByTestId('lens-switcher')
  await switcher.click()
  await expect(page.getByTestId('canvas-popover-backdrop')).toHaveCount(0)
  await page.getByTestId('graph-canvas').click({ position: { x: 500, y: 400 } })
  await expect(switcher).toHaveAttribute('aria-expanded', 'false')

  await switcher.click()
  await page.keyboard.press('Escape')
  await expect(switcher).toHaveAttribute('aria-expanded', 'false')

  const views = page.getByTestId('views-switcher')
  await views.click()
  await page.keyboard.press('Escape')
  await expect(views).toHaveAttribute('aria-expanded', 'false')
})
